### ISSUE TITLE
[error] 21_pod5-liveness-http.yaml中的args错误 

### ISSUE THREAD

**Issue by SteveWANG-sjtu** [rebirthmonkey/k8s#17]
line 12:       command: ['sh', '-c', '/server']
应改为
command: ['/server']

**Comment by SteveWANG-sjtu** [comment]
如果换源为 
- image: registry.hub.docker.com/davidliyutong/liveness:latest
那么应该更换line 12的command

**Comment by davidliyutong** [comment]
> 如果换源为
> 
> * image: registry.hub.docker.com/davidliyutong/liveness:latest
>   那么应该更换line 12的command

是k8s.gcr.io/liveness镜像发生了变化，移除了sh。davidliyutong/liveness同步了更改
